### ISSUE TITLE
adamre doesn't come to WnW

### ISSUE THREAD

**Issue by haydenmc** [AdamTReineke/lwc-card-game#1] opened 2020-02-07 18:59 UTC
1. Go to work night Wednesday

Expect: Adam shows up
Actual: Adam does not show up

Note: 100% repro.

**Comment by GHeadley** [comment] 2020-02-07 19:03
I am also having this issue. My attempts at fixing this issue:

- Complain to Hayden
- Cry nightly

Nothing seems to work. Would love to see this get fixed as its blocking our friendship.

**Comment by sidiesen** [comment] 2020-02-07 19:40
Yeah I have been running into similar issues recently. I tried reflashing my memory, supercharging the flux capacitors and even started to disengage the ventral nanobrane phase converter but everytime I log into WnW I still get errors about the missing "adamre" module.

It's starting to seriously affect my user experience.

I know the manufacturer recently underwent a merger, I hope that doesn't mean they're dropping their WnW support. I am glad to see though that there is still some ongoing contributions to the "lunch of champions" efforts.

**Comment by AdamTReineke** [comment] 2020-02-07 23:25
Closing, by design. WnW is incompatible with dependency `adam/calendar@latest` due to a permanent schedule conflict.

**Closed by AdamTReineke** 2020-02-07 23:25 UTC

**Comment by haydenmc** [comment] 2020-02-08 00:45
Booo hisssss
